const REPORT_TEXT_1 = `Busey ipsum dolor sit amet. You ever roasted doughnuts?Have you urinated? Have you drained your bladder? Are you free? Because if you haven't it will only come out later. I'm giving you some information that your bodily fluids may penetrate your clothing fibre's without warning.
When you get lost in your imaginatory vagueness, your foresight will become a nimble vagrant.It's good to yell at people and tell people that you're from Tennesee, so that way you'll be safe.Have you urinated? Have you drained your bladder? Are you free? Because if you haven't it will only come out later. I'm giving you some information that your bodily fluids may penetrate your clothing fibre's without warning.
The magic Indian is a mysterious spiritual force, and we're going to Cathedral Rock, and that's the vortex of the heart.You ever roasted doughnuts?It's good to yell at people and tell people that you're from Tennesee, so that way you'll be safe.Listen to the silence. And when the silence is deafening, you're in the center of your own universe.
These kind of things only happen for the first time once.`;
const REPORT_TEXT_2 = `Have you urinated? You ever roasted doughnuts? Have you drained your bladder? Are you free? Because if you haven't it will only come out later. I'm giving you some information that your bodily fluids may penetrate your clothing fibre's without warning.
When you get lost in your imaginatory vagueness, your foresight will become a nimble vagrant.It's good to yell at people and tell people that you're from Tennesee, so that way you'll be safe.Have you urinated? Have you drained your bladder? Are you free? Because if you haven't it will only come out later. I'm giving you some information that your bodily fluids may penetrate your clothing fibre's without warning.
The magic Indian is a mysterious spiritual force, and we're going to Cathedral Rock, and that's the vortex of the heart.You ever roasted doughnuts?It's good to yell at people and tell people that you're from Tennesee, so that way you'll be safe.Listen to the silence. And when the silence is deafening, you're in the center of your own universe.
These kind of things only happen for the first time once.When you get lost in your imaginatory vagueness, your foresight will become a nimble vagrant.The best way to communicate is compatible. Compatible communication is listening with open ears and an open mind, and not being fearful or judgemental about what you're hearing.
I would like to give you a backstage pass to my imagination.You ever roasted doughnuts?The magic Indian is a mysterious spiritual force, and we're going to Cathedral Rock, and that's the vortex of the heart.I wrestled a bear once. A 750lbs black bear.`;
const REPORT_TEXT_3 = `When you get lost in your imaginatory vagueness, your foresight will become a nimble vagrant.The best way to communicate is compatible. Compatible communication is listening with open ears and an open mind, and not being fearful or judgemental about what you're hearing.
I would like to give you a backstage pass to my imagination.You ever roasted doughnuts?The magic Indian is a mysterious spiritual force, and we're going to Cathedral Rock, and that's the vortex of the heart.I wrestled a bear once. A 750lbs black bear.`;
const REPORT_TEXT_4 = `Have you urinated? Have you drained your bladder? Are you free? Because if you haven't it will only come out later. I'm giving you some information that your bodily fluids may penetrate your clothing fibre's without warning.
When you get lost in your imaginatory vagueness, your foresight will become a nimble vagrant.It's good to yell at people and tell people that you're from Tennesee, so that way you'll be safe.Have you urinated? Have you drained your bladder? Are you free? Because if you haven't it will only come out later. I'm giving you some information that your bodily fluids may penetrate your clothing fibre's without warning.
The magic Indian is a mysterious spiritual force, and we're going to Cathedral Rock, and that's the vortex of the heart.You ever roasted doughnuts?It's good to yell at people and tell people that you're from Tennesee, so that way you'll be safe.Listen to the silence. And when the silence is deafening, you're in the center of your own universe.
These kind of things only happen for the first time once.You ever roasted doughnuts?The magic Indian is a mysterious spiritual force, and we're going to Cathedral Rock, and that's the vortex of the heart.I wrestled a bear once. A 750lbs black bear.`;
const REPORT_TEXT_5 = `When you get lost in your imaginatory vagueness, your foresight will become a nimble vagrant.The best way to communicate is compatible. Compatible communication is listening with open ears and an open mind, and not being fearful or judgemental about what you're hearing.
I would like to give you a backstage pass to my imagination.You ever roasted doughnuts?The magic Indian is a mysterious spiritual force, and we're going to Cathedral Rock, and that's the vortex of the heart.I wrestled a bear once. A 750lbs black bear.`;
const REPORT_TEXT_6 = `Your foresight will become a nimble vagrant.It's good to yell at people and tell people that you're from Tennesee, so that way you'll be safe.Have you urinated? Have you drained your bladder? Are you free? Because if you haven't it will only come out later. I'm giving you some information that your bodily fluids may penetrate your clothing fibre's without warning.
The magic Indian is a mysterious spiritual force, and we're going to Cathedral Rock, and that's the vortex of the heart.You ever roasted doughnuts?It's good to yell at people and tell people that you're from Tennesee, so that way you'll be safe.Listen to the silence. And when the silence is deafening, you're in the center of your own universe.
These kind of things only happen for the first time once.You ever roasted doughnuts?The magic Indian is a mysterious spiritual force, and we're going to Cathedral Rock, and that's the vortex of the heart.I wrestled a bear once. A 750lbs black bear.`;

const EVENT_TEXT_1 = `Das Betreten des Cinema Arlecchino hatte in diesem Jahr etwas Irritierendes. Gefühlte zwanzig Meter nach dem Vorhang, der die Lobby vom Kinosaal trennt, stand ein hübscher Kerl im Karohemd, hieß jeden einzelnen Besucher mit „Salve“ willkommen und verbeugte sich. Wie alle anderen war auch ich erstmal überrumpelt, fragte mich kurz, ob wir uns vielleicht kennen, erwiderte dann zögerlich den Gruß und schaute mir das Schauspiel nach einigen Schritten nochmal aus der Ferne an. Wirklich einordnen konnte ich dieses Ritual nicht. War das nun die Bologneser Gastfreundschaft? Eine Performance? Oder war der Gute einfach nicht ganz dicht? In den darauffolgenden Tagen habe ich ihn immer wieder beobachtet, etwa wie er Besuchern freie Plätze zuwies oder während der Projektion Kontrollgänge machte. Ob er aber wirklich zum Kinopersonal gehörte, blieb ein Geheimnis. Während meine Begleiterinnen sich sicher waren, dass der junge Mann einfach ein bisschen verrückt sei, fragte ich mich eher, ob die Schuld vielleicht bei uns zu suchen ist, weil wir solch offensiver Nettigkeit automatisch misstrauen.`;
const EVENT_TEXT_2 = `Streifzüge durch die Seitengassen der deutschen Filmgeschichte verbinden sich mit Schlaglichtern auf das Gegenwartskino (zu Gast: Eckhart Schmidt und Garegin Vanisian) und Ausflügen in andere Länder und Kontinente. Lange wurde in nationalen und internationalen Archiven gegraben, fragile Raritäten geprüft und unglaubliche Zelluloid-Schätze gehoben, die mitunter eine weite Reise angetreten haben - darunter von einem HK-Säulenheiligen inszenierte, schwarz-weiße US-Erotica der 60er, die von der IMDb als verschollen gelistet wird, jedoch von uns aufgespürt wurde. Von deutschen Wohnzimmern, Garagen und Toiletten bis in brasilianische Spelunken, japanische Gemächer und den indischen Ozean führt die filmische Reise für alle, die gegenüber den Besonderheiten und Seltsamkeiten des Kinos aufgeschlossen sind. Lasst euch entführen, verführen und oft einfach überraschen! Das Programm wird spontan ergänzt von „Videoknüppeln“ als nächtlichen Überraschungsfilmen.`;
const EVENT_TEXT_3 = `Dieser Moment passt gut zu dem Retrospektiven-Festival Il Cinema Ritrovato. Auch in seiner 31. Ausgabe wirkt alles noch ein wenig improvisiert, noch nicht so professionell durchorganisiert, wie man das von anderen Veranstaltungen dieser Art kennt. Das hat manchmal zwar seinen Charme, kann sich aber auch unangenehm bemerkbar machen. Etwa wenn der Filmvorführer mal wieder etwas länger braucht, um zu merken, dass das Bild unscharf ist oder die Tonspur aussetzt. Zum Glück kann man in solchen Fällen auf das engagierte, überwiegend aus Fachbesuchern bestehende Publikum vertrauen, das den Projektionisten mit lautstarken „Audio“- oder „Fuoco“-Rufen auf sein Versäumnis aufmerksam macht. Abgesehen von solchen Wermutstropfen wirkt es aber so, als wäre das Il Cinema Ritrovato mittlerweile erwachsen geworden. Was als dreitägiges Event begann, ist zu einem Festival geworden, das mit jedem Jahr noch mehr Filme und Reihen präsentiert; steigende Besucherzahlen inklusive.`;
const EVENT_TEXT_4 = `Schmetterlinge, die bei Berührung töten; ein Ferienidyll, durch das sich Lavaströme fressen; ein FBI-Undercoveragent mit zahllosen Oneliner-Einsätzen und der Statur eines Navy Seals; ein sonnenbebrillter Killer im Anzug, dessen Weiß sich zusehends blutrot färbt; ein Mad Scientist mit gleichermaßen extravaganten Roben wie absurd schlechten Zähnen: Vom 11. bis 13. November fand im gleichermaßen enthusiastischen wie (genre-)filmhistorisch versierten Nürnberger KommKino wieder das gänzlich von 35-mm-Kopien projizierte Karacho – Festival des Actionfilms statt. Das Programm ist abwechslungsreicher, als man bei einem Ein-Genre-Festival vermuten könnte. Action ist hier der Oberbegriff für alles, was physisch ausgreift, sozusagen die Klammer, innerhalb derer sich diverse Genrespielarten des Spektakels und der Kinetik zusammenfinden. Gemeinsam haben die zusammengestellten Filme, dass sie bedingungslos an die Macht der Bilder (und Töne) glauben, dass sie stetig mit ihren Reizen in den „Schutzraum“ des Kinoraums vordringen. Dieses Jahr gab es unter anderem einen für die DEFA (nicht zuletzt wegen des merklichen Fernwehs) untypischen Rennfahrerfilm (Rivalen am Steuer, 1957), einen japanischen Monsterfilm samt liebevollen Städteminiaturen und Gummianzügen (King Kong – Frankensteins Sohn / Kingu Kongu no gyakushū, 1967), pathosgetränktes „Heroic Bloodshed“ des Shootout- und Bodycount-Megalomanen John Woo (The Killer, 1989), großbudgetiertes und -orchestriertes Hollywood-Katastrophenkino (Dante’s Peak, 1997), Tsui Harks vom zeitgenössischen Eurohorror beeinflusstes Martial-Arts-Debüt Die Todesgrotten der Shaolin (The Butterfly Murders, 1979) und eben das, was man auf Anhieb mit Actionkino in Verbindung bringt: muskelbepacktes und sich selbst nicht allzu ernst nehmendes Schwarzenegger-80er-Kino (Der City Hai / Raw Deal, 1986) oder eine für den boomenden Videomarkt gedrehte Cannon-Films-Produktion mit dem leicht melancholisch dreinblickenden Michael Dudikoff (The Human Shield, 1991).`;
const EVENT_TEXT_5 = `Italowestern, Giallo, Poliziottesco, Gothic-Horror, Science-Fiction in unterschiedlichen Variationen, Drogendrama, Disco-, Mondo- und Mantel-und-Degen-Film … Diese unvollständige Aufzählung der Genres deutet hoffentlich an, dass auch die 8. Ausgabe des Terza Visione – Festival des italienischen Genrefilms einen bunten Strauß an Eindrücken bereithielt. Nach dem letztjährigen Intermezzo in der Karlsruher Schauburg fand das analog projizierte Retrofilmfestival wieder in der gewohnten Spielstätte des Deutschen Filminstituts und Filmmuseums in Frankfurt am Main statt. Der Filmmuseumsstatus und die nicht mehr allzu prekäre Pandemiesituation machten es möglich, in puncto übernationaler Kopienbeschaffung wieder mehr aus dem Vollen zu schöpfen. Zugleich wurde aber in den Filmeinführungen häufig plastisch der steinige Weg beschrieben, bis man ein von möglichst farbechten Kopien bestrittenes Programm überhaupt präsentieren kann.`;
const EVENT_TEXT_6 = `Allerorten wird die 60. Berlinale bilanziert. Das Filmfest selbst regeneriert sich jedes Jahr wunderhaft aufs Neue; der Wettbewerb aber gleicht immer mehr einem Festival des gescheiterten Films, wie Christine Fischer (FREITAG) schreibt. Der Wettbewerb fiel enttäuschend für Dominik Kamalzadeh (STANDARD) aus. Dieter Kosslick ist ein Pragmatiker, ein gut gelaunter Macher, der das Festival ungemein belebt habt, aber mit seiner Wettbewerbspolitik ist er in einer Sackgasse angelangt, kritisiert Michael Althen (FAZ): Filmgeschichte passiert woanders. Um mit den Worten des Festivalchefs zu sprechen: Die Berlinale war cool, aber dieses modische Wort passt nicht zu der Kompromissveranstaltung, die die Berlinale mittlerweile geworden ist, findet Anke Westphal (BLZ).`;

export const MOCKED_CITIES = [
  'Aschaffenburg',
  'Aurich',
  'Backnang',
  'Bad Salzungen',
  'Berlin',
  'Bonn',
  'Braunschweig',
  'Burgdorf',
  'Buxtehude',
  'Chemnitz',
  'Düren',
  'Essen',
  'Finsterwalde',
  'Frankenthal',
  'Frankfurt am Main',
  'Freudenstadt',
  'Gera',
  'Halle (Saale)',
  'Hamburg',
  'Hannover',
  'Hillesheim',
  'Konstanz',
  'Langenfeld',
  'Leipzig',
  'Leonberg',
  'Lohne',
  'Marburg',
  'Mönchengladbach',
  'München',
  'Münster',
  'Nürnberg',
  'Oberhausen',
  'Paderborn',
  'Quickborn',
  'Solingen',
  'Stuttgart',
  'Türkheim',
  'Uelzen',
  'Wolfenbüttel',
  'Wolfsburg',
];
export const MOCKED_CINEMA_NAMES = [
  'Roxy Kino',
  'Apollo Service Kino',
  'Bali',
  'Casino',
  'Carolinenhof-Kino',
  'Traumpalast Backnang',
  'Kino Universum',
  'Kino-Center Rhein-Ahr',
  'pab Kinocenter',
  'Bambi & Camera',
  'Open Air Kino im Bad Vilbeler Freibad',
  'Kino Alte Mühle',
  'Zoo-Palast',
  'Thalia',
  'Filmtheater Capitol',
  'Traumpalast Biberach',
  'Kinodrom Multiplex',
  'Woki',
  'Centraltheater',
  'C1 Cinema',
  'Kino Universum',
  'Neue Schauburg',
  'Starmexx',
  'City Kino Buxtehude',
  'Metropol',
  'Dersa Kino-Center',
  'Lichtburg Center',
  'Das Lumen Filmtheater',
  'Lichtburg und Sabu',
  'Weltspiegel',
  'Lux',
  'Cinema',
  'Harmonie',
  'Linden-Theater',
  'Subiaco im Kurhaus',
  'Gloria Kino Center',
  'Park-Lichtspiele',
  'Casino',
  'Metropol Kino',
  'Goli Theater Goch',
  'Filmwelt Grünstadt',
  'Cinexx',
  'The Light Cinema',
  'Savoy',
  'Passage Kino Hamburg',
  'Astor Grand Cinema',
  'Filmwelt',
  'Eifel-Film-Bühne',
  'Berli Theater',
  'Kino-Center',
  'Capitol-Theater',
  'Tichelpark Kleve',
  'Zebra Kommunales Kino Konstanz e.V.',
  'Rex',
  'Das Andere Kino',
  'Regina-Palast',
  'Luru-Kino in der Spinnerei',
  'Lichtspielhaus',
  'Traumpalast Leonberg',
  'Capitol-Kinocenter',
  'Cineplex',
  'Movie im Luitpoldhaus',
  'Linden-Lichtspiele',
  'Comet Cine Center',
  'Haus Zoar',
  'Filmpassage',
  'Mathäser Filmpalast',
  'Gloria-Palast',
  'Cineplex',
  'Schlosstheater',
  'Kinocenter',
  'Wied Scala',
  'Corso Film Casino',
  'Lumos Lichtspiele & Lounge',
  'Cinecitta',
  'Lichtburg Filmpalast',
  'Pollux',
  'Kino Papenburg',
  'Union-Theater Plochingen',
  'Schauburg Filmtheater',
  'Lichtburg',
  'Beluga Kino',
  'Burgtheater',
  'Schauburg',
  'Cinetech das Erlebniskino',
  'Kinocenter',
  'Schmelzer Lichtspiele',
  'LichtSpiel e.V.',
  'Traumpalast Schorndorf',
  'Das Lumen Filmtheater',
  'Zentral-Theater',
  'Citydom',
  'Gloria',
  'Central Theater',
  'Filmhaus-Huber in Türkheim',
  'Central-Theater',
  'Burg-Theater',
  'Neue Post Lichtspiele',
  'Capitol-Theater',
  'Capitol-Cinema-Center',
  'LiLi-Servicekino',
  'Kino Astoria',
  'Filmpalast',
  'Cinema',
  'Delphin Palast',
  'Amper-Lichtspiele',
  'Club-Kino',
];
export const MOCKED_CINEMA_IMAGES = [
  'luru-kino.jpeg',
  'zoo_1.jpg',
  'zoo_2.jpg',
  'zoo_3.jpg',
  'varnsdorf.jpg',
  'new_beverly.jpg',
];
export const MOCKED_STREETS = [
  'Brnoer Straße',
  'Bruno-Leuschner-Straße',
  'Bruno-Plache-Straße',
  'Dimitroffstraße zwischen Harkort- und Beethovenstraße',
  'Dr.-Kurt-Fischer-Straße',
  'Erich-Ferl-Straße',
  'Ernst-Grube-Straße',
  'Ernst-Thälmann-Straße',
  'Frieda-Hockauf-Straße',
  'Friedrich-Engels-Platz',
  'Friedrich-Ludwig-Jahn-Allee',
  'Fritz-Austel-Straße',
  'Georgi-Dimitroff-Platz',
  'Ho-Chi-Minh-Straße',
  'Hugo-Joachim-Straße',
  'Karl-Marx-Platz',
  'Karl-Marx-Städter-Straße',
  'Krakower Straße',
  'Kurt-Kühn-Straße',
  'Leninstraße',
  'Maurice-Thorez-Straße',
  'Otto-Nuschke-Straße',
  'Paul-Heine-Straße',
  'Philipp-Müller-Straße',
  'Platz der Republik',
  'Richard-Sorge-Straße',
  'Rudkowskystraße',
  'Rudolf-Hartig-Straße',
  'Spartakusstraße',
  'Straße der Aktivisten',
  'Straße der Bauarbeiter',
  'Straße der Befreiung',
  'Straße der DSF',
  'Straße der Jugend',
  'Straße der Jungen Pioniere',
  'Straße der Nationalen Volksarmee',
  'Straße der Solidarität',
  'Straße der Völkerfreundschaft',
  'Straße der Waffenbrüderschaft',
  'Straße des Komsomol',
  'Wilhelm-Liebknecht-Platz',
  'Wilhelm-Pieck-Allee',
];
export const MOCKED_EVENT_NAMES = [
  'Karacho',
  'Terza Visione',
  'Hofbauer Kongress',
  'Il Cinema Ritrovato',
  '70mm Festival Varnsdorf',
  '70mm Festival Karlsruhe',
  'Achternbusch Reihe',
  'Vorsicht Liebe! Lebensgefahr!',
  'Stummfilmkino im Luru-Kino',
  'Donis Horror-Doppel',
  'George Romero Reihe',
  'Luru-Archive',
  'Die gelbe Gefahr!',
  'Jesus Franco Reihe',
  'Pink Weekend',
  'Besonders wertlos',
  'Giallo Special',
  'Berlinale Analog Auswahl',
  'Karacho',
  'Terza Visione',
  'Hofbauer Kongress',
  'Il Cinema Ritrovato',
  '70mm Festival Varnsdorf',
  '70mm Festival Karlsruhe',
  'Achternbusch Reihe',
  'Vorsicht Liebe! Lebensgefahr!',
  'Stummfilmkino im Luru-Kino',
  'Donis Horror-Doppel',
  'George Romero Reihe',
  'Luru-Archive',
  'Die gelbe Gefahr!',
  'Jesus Franco Reihe',
  'Pink Weekend',
  'Besonders wertlos',
  'Giallo Special',
  'Berlinale Analog Auswahl',
  'Karacho',
  'Terza Visione',
  'Hofbauer Kongress',
  'Il Cinema Ritrovato',
  '70mm Festival Varnsdorf',
  '70mm Festival Karlsruhe',
  'Achternbusch Reihe',
  'Vorsicht Liebe! Lebensgefahr!',
  'Stummfilmkino im Luru-Kino',
  'Donis Horror-Doppel',
  'George Romero Reihe',
  'Luru-Archive',
  'Die gelbe Gefahr!',
  'Jesus Franco Reihe',
  'Pink Weekend',
  'Besonders wertlos',
  'Giallo Special',
  'Berlinale Analog Auswahl',
  'Karacho',
  'Terza Visione',
  'Hofbauer Kongress',
  'Il Cinema Ritrovato',
  '70mm Festival Varnsdorf',
  '70mm Festival Karlsruhe',
  'Achternbusch Reihe',
  'Vorsicht Liebe! Lebensgefahr!',
  'Stummfilmkino im Luru-Kino',
  'Donis Horror-Doppel',
  'George Romero Reihe',
  'Luru-Archive',
  'Die gelbe Gefahr!',
  'Jesus Franco Reihe',
  'Pink Weekend',
  'Besonders wertlos',
  'Giallo Special',
  'Berlinale Analog Auswahl',
];
export const MOCKED_PROJECTION_NAMES = [
  'Der Pate (1972)',
  'The Dark Knight (2008)',
  'Der Pate 2 (1974)',
  'Die zwölf Geschworenen (1957)',
  'Schindlers Liste (1993)',
  'Der Herr der Ringe: Die Rückkehr des Königs (2003)',
  'Pulp Fiction (1994)',
  'Der Herr der Ringe: Die Gefährten (2001)',
  'Zwei glorreiche Halunken (1966)',
  'Forrest Gump (1994)',
  'Fight Club (1999)',
  'Der Herr der Ringe: Die zwei Türme (2002)',
  'Inception (2010)',
  'Das Imperium schlägt zurück (1980)',
  'Matrix (1999)',
  'GoodFellas - Drei Jahrzehnte in der Mafia (1990)',
  'Einer flog über das Kuckucksnest (1975)',
  'Sieben (1995)',
  'Die sieben Samurai (1954)',
  'Ist das Leben nicht schön? (1946)',
  'Das Schweigen der Lämmer (1991)',
  'Der Soldat James Ryan (1998)',
  'City of God (2002)',
  'Interstellar (2014)',
  'Das Leben ist schön (1997)',
  'The Green Mile (1999)',
  'Krieg der Sterne (1977)',
  'Terminator 2: Tag der Abrechnung (1991)',
  'Zurück in die Zukunft (1985)',
  'Chihiros Reise ins Zauberland (2001)',
  'Der Pianist (2002)',
  'Psycho (1960)',
  'Parasite (2019)',
  'Léon: Der Profi (1994)',
  'Der König der Löwen (1994)',
  'Gladiator (2000)',
  'American History X (1998)',
  'Departed: Unter Feinden (2006)',
  'Prestige - Die Meister der Magie (2006)',
  'Whiplash (2014)',
  'Die üblichen Verdächtigen (1995)',
  'Casablanca (1942)',
  'Die letzten Glühwürmchen (1988)',
  'Harakiri (1962)',
  'Ziemlich beste Freunde (2011)',
  'Moderne Zeiten (1936)',
  'Spiel mir das Lied vom Tod (1968)',
  'Cinema Paradiso (1988)',
  'Das Fenster zum Hof (1954)',
  'Alien - Das unheimliche Wesen aus einer fremden Welt (1979)',
  'Lichter der Großstadt - Eine Komödien-Romance als Pantomime (1931)',
  'Apocalypse Now (1979)',
  'Memento (2000)',
  'Django Unchained (2012)',
  'Jäger des verlorenen Schatzes (1981)',
  'WALL·E - Der Letzte räumt die Erde auf (2008)',
  'Das Leben der Anderen (2006)',
  'Boulevard der Dämmerung (1950)',
  'Wege zum Ruhm (1957)',
  'Shining (1980)',
  'Der große Diktator (1940)',
  'Avengers: Infinity War (2018)',
  'Zeugin der Anklage (1957)',
  'Alien 2 - Die Rückkehr (1986)',
  'Spider-Man: A New Universe (2018)',
  'American Beauty (1999)',
  'Seltsam oder: Wie ich lernte, die Bombe zu lieben (1964)',
  'The Dark Knight Rises (2012)',
  'Oldboy (2003)',
  'Inglourious Basterds (2009)',
  'Amadeus (1984)',
  'Coco: Lebendiger als das Leben (2017)',
  'Toy Story (1995)',
  'Joker (2019)',
  'Braveheart (1995)',
  'Das Boot (1981)',
  'Avengers: Endgame (2019)',
  'Prinzessin Mononoke (1997)',
  'Es war einmal in Amerika (1984)',
  'Good Will Hunting: Der gute Will Hunting (1997)',
  '(2016)',
  'Du sollst mein Glücksstern sein (1952)',
  '3 Idiots (2009)',
  'Requiem for a Dream (2000)',
  'Zwischen Himmel und Hölle (1963)',
  'Toy Story 3 (2010)',
  'Capernaum: Stadt der Hoffnung (2018)',
  'Die Rückkehr der Jedi-Ritter (1983)',
  'Vergiss mein nicht (2004)',
  '2001: Odyssee im Weltraum (1968)',
  'Komm und sieh (1985)',
  'Reservoir Dogs: Wilde Hunde (1992)',
  'Die Jagd (2012)',
  'Citizen Kane (1941)',
  'M: Eine Stadt sucht einen Mörder (1931)',
  'Lawrence von Arabien (1962)',
  'Der unsichtbare Dritte (1959)',
  'Ikiru - Einmal wirklich leben (1952)',
  'Aus dem Reich der Toten (1958)',
  'Das Appartement (1960)',
  'Die fabelhafte Welt der Amelie (2001)',
  'Uhrwerk Orange (1971)',
  'Frau ohne Gewissen (1944)',
  'Full Metal Jacket (1987)',
  'Scarface (1983)',
  'Hamilton (2020)',
  'Die Frau die singt - Incendies (2010)',
  'Heat (1995)',
  'Wer die Nachtigall stört (1962)',
  'Oben (2009)',
  'Der Clou (1973)',
  'Nader und Simin - eine Trennung (2011)',
  'Metropolis (1927)',
  'Taxi Driver (1976)',
  'Confidential (1997)',
  'Stirb langsam (1988)',
  'Snatch: Schweine und Diamanten (2000)',
  'Indiana Jones und der letzte Kreuzzug (1989)',
  'Top Gun: Maverick (2022)',
  'Fahrraddiebe',
];
export const MOCKED_REPORT_NAMES = [
  ...MOCKED_CINEMA_NAMES,
  ...MOCKED_EVENT_NAMES,
];
export const MOCKED_REPORT_TEXTS = [
  REPORT_TEXT_1,
  REPORT_TEXT_2,
  REPORT_TEXT_3,
  REPORT_TEXT_4,
  REPORT_TEXT_5,
  REPORT_TEXT_6,
];
export const MOCKED_EVENT_TEXTS = [
  EVENT_TEXT_1,
  EVENT_TEXT_2,
  EVENT_TEXT_3,
  EVENT_TEXT_4,
  EVENT_TEXT_5,
  EVENT_TEXT_6,
];
export const MOCKED_TMDBIDS = [
  '18331',
  '38655',
  '36818',
  '42305',
  '24062',
  '35189',
  '18973',
  '15788',
  '42581',
  '43317',
  '53441',
  '44747',
  '58182',
];
export const MOCKED_TMDB_QUERIES = [
  'fart',
  'killer',
  'dance',
  'underground',
  'flight',
  'gunfight',
  'graveyard',
  'water',
  'dark',
  'sail',
  'red',
  'blood',
  'romance',
  'porno',
  'sex',
  'cobra',
  'heaven',
  'hold',
];
